cache:
  directories:
  - node_modules
language: node_js
node_js:
  8
branches:
  only:
  - master
script:
- yarn install
- yarn build
install:
  npm install -g firebase-tools
after_success:
- firebase use --token ${FIREBASE_TOKEN}
- firebase use --add ${PROJECT_ID}
- firebase deploy --token "${FIREBASE_TOKEN}"